### ISSUE TITLE
FLOPART_Data Issue 

### ISSUE THREAD

**Issue by jkaufy** [tdhock/FLOPART#4]
@tdhock 

When running FLOPART_data:

For the label: 23986621 | 23987411 | peakEnd |  in specific returns rows: 2287 | 2293, which gives chromStart | chromEnd values of 23987741 | 23987800. This isn't within the range of the original label.

[FLOPART_data_issue_counts.csv](https://github.com/tdhock/FLOPART/files/8654328/FLOPART_data_issue_counts.csv)
[FLOPART_data_issue_labels.csv](https://github.com/tdhock/FLOPART/files/8654329/FLOPART_data_issue_labels.csv)

This seems to fix that issue (I might not be understanding the issue) :

```
labelToRow <- function (counts, label.dt){
    counts[, row := seq.int(.N)]
    start_vec <- c()
    end_vec <- c()
    for (row in 1:nrow(label.dt)){
        label <- label.dt[row]
        start_vec <- c(start_vec,counts[chromStart > label$chromStart][1]$row)
        end_vec <- c(end_vec, tail(counts[chromEnd < label$chromEnd],1)$row)
    }
    
    label.dt[, start:= start_vec]
    label.dt[, end:= end_vec]
    
    return(label.dt)
}

```

**Comment by tdhock** [comment]
hi @jkaufy thanks for the detailed report. I am able to replicate your issue via this code:
```r
> counts.dt <- data.table::fread("FLOPART-issue4-counts.csv")
> labels.dt <- data.table::fread("FLOPART-issue4-labels.csv")
> data.list <- FLOPART::FLOPART_data(counts.dt, labels.dt)
> data.list$label_dt[7]
   chromStart chromEnd annotation type firstRow lastRow
1:   23986621 23987411    peakEnd   -1     2287    2293
> counts.dt$chromStart[2287]
[1] 23987741
> counts.dt$chromEnd[2293]
[1] 23987800
```
The code above shows that the seventh label gets assigned firstRow=2287 and lastRow=2293, and when you look at the corresponding rows of the counts.dt (input to FLOPART_data) then you get the values 23987741,23987800 which are indeed not the same as the start/end of the label 23986621,23987411.
This is not a bug in FLOPART_data, but instead two distinct issues in how you are interpreting the output.
1. the firstRow/lastRow are 0-based for passing to the C++ code, not 1-based as is usual in R. This is actually documented in ?FLOPART_data, section Value: "firstRow/lastRow are 0-based indices passed to C++ code". So you need to add 1 to firstRow/lastRow to R code for indexing.
2. the firstRow/lastRow refer to the rows of the `coverage_dt` element of the output/value returned from FLOPART_data (which is not be the same as the counts.dt input to FLOPART_data -- there are additional rows added to handle the labels). This is not so clearly documented so I will update the docs to clarify.
Making those two changes to the code above we get the following,
```r
> data.list$label_dt[7]
   chromStart chromEnd annotation type firstRow lastRow
1:   23986621 23987411    peakEnd   -1     2287    2293
> data.list$coverage_dt$chromStart[2288]
[1] 23986621
> data.list$coverage_dt$chromEnd[2294]
[1] 23987411
```
The code above shows that the chromStart/End values are actually consistent with the original label and firstRow/lastRow values, so there is no bug in FLOPART_data.
Does that solve your issue?

**Comment by jkaufy** [comment]
Yes, I think this solved the issue.
