### ISSUE TITLE
firstRow/lastRow are potentially confusing

### ISSUE THREAD

**Issue by tdhock** [tdhock/FLOPART#5]
Hey @jkaufy this is related to your recent issue #4 
The output of FLOPART is potentially confusing because both label_dt and segments_dt have columns named firstRow/lastRow but they are not interpreted in the same way.
- label_dt firstRow/lastRow are 0-indexed.
- segments_dt firstRow/lastRow are 1-indexed.
Here is an example
```r
chromEnd <- seq(10, 30, by=10)
counts <- data.frame(
  chromStart=chromEnd-10L,
  chromEnd,
  count=c(200,500,500))
labels <- data.frame(
  chromStart=5,
  chromEnd=15,
  annotation="noPeaks")
fit <- FLOPART::FLOPART(counts,labels,penalty=5)
fit[c("coverage_dt", "label_dt", "segments_dt")]
```
That gives
```r
> fit[c("coverage_dt", "label_dt", "segments_dt")]
$coverage_dt
   chromStart chromEnd count weight
1:          0        5   200      5
2:          5       10   200      5
3:         10       15   500      5
4:         15       30   500     15

$label_dt
   chromStart chromEnd annotation type firstRow lastRow
1:          5       15    noPeaks    0        1       2

$segments_dt
   mean firstRow lastRow state chromStart chromEnd     status
1:  300        1       3     0          0       15 background
2:  500        4       4     4         15       30       peak
```
It is clear from the output above that label_dt firstRow=1 and lastRow=2 refers to the second/third rows of coverage_dt. However in segments_dt we have firstRow=1 and lastRow=3 which refers to the first three rows of coverage_dt. This is potentially confusing because in the one case the third row of coverage_dt is described as lastRow=2 whereas in the other it is lastRow=3.
To fix this possible point of confusion I think it would be good to make them consistent. Either we make both 1-indexed (need to change label_dt) or we make both 0-indexed (need to change segments_dt). Do you have any preference? I would think that it would be better to make both 1-indexed since that is the usual convention in R.

**Comment by tdhock** [comment]
another option would be to just remove the firstRow/lastRow columns from segments_dt?

**Comment by jkaufy** [comment]
@tdhock i think removing those columns would be the best option.

**Comment by tdhock** [comment]
fixed by https://github.com/tdhock/FLOPART/commit/ba943cc42a5f6fd46f1a538a7048931503620f4d
